{
  "Software_Repo_MappingId": null,
  "Software_RepoId": "f6b863cd-8f1c-4583-8bc5-ee59e86e5cf1",
  "Software_Name": "Python 3.12.5 (64-bit)",
  "CVEID": "CVE-2023-38898",
  "Summary": "An issue in Python cpython v.3.7 allows an attacker to obtain sensitive information via the _asyncio._swap_current_task component. NOTE: this is disputed by the vendor because (1) neither 3.7 nor any other release is affected (it is a bug in some 3.12 pre-releases); (2) there are no common scenarios in which an adversary can call _asyncio._swap_current_task but does not already have the ability to call arbitrary functions; and (3) there are no common scenarios in which sensitive information, which is not already accessible to an adversary, becomes accessible through this bug.",
  "LastUpdate": 0,
  "CVEE": {
    "CVEEId": "CVE-2023-38898",
    "CVSS_V2_baseScore": null,
    "CVSS_V2_Data": null,
    "CVSS_V3_baseScore": 5.3,
    "CVSS_V3_Data": "{\"version\":\"3.1\",\"baseScore\":5.3,\"accessVector\":null,\"vectorString\":\"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N\",\"authentication\":null,\"integrityImpact\":\"NONE\",\"accessComplexity\":null,\"availabilityImpact\":\"NONE\",\"confidentialityImpact\":\"LOW\",\"scope\":\"UNCHANGED\",\"attackVector\":\"NETWORK\",\"baseSeverity\":\"MEDIUM\",\"userInteraction\":\"NONE\",\"attackComplexity\":\"LOW\",\"privilegesRequired\":\"NONE\"}",
    "PublishedDate": "2023-08-15T17:15:12.187",
    "ModifyDate": "2024-11-21T08:14:24.253",
    "VulnStatus": "Modified",
    "JsonData": "{\"id\": \"CVE-2023-38898\", \"summary\": \"An issue in Python cpython v.3.7 allows an attacker to obtain sensitive information via the _asyncio._swap_current_task component. NOTE: this is disputed by the vendor because (1) neither 3.7 nor any other release is affected (it is a bug in some 3.12 pre-releases); (2) there are no common scenarios in which an adversary can call _asyncio._swap_current_task but does not already have the ability to call arbitrary functions; and (3) there are no common scenarios in which sensitive information, which is not already accessible to an adversary, becomes accessible through this bug.\", \"created_at\": \"2023-08-15T17:15:12Z\", \"updated_at\": \"2024-11-21T08:14:24Z\", \"cvss\": {\"v2\": null, \"v3\": 5.3}, \"vendors\": {\"python\": [\"python\"]}, \"cwes\": [\"NVD-CWE-Other\"], \"raw_nvd_data\": {\"id\": \"CVE-2023-38898\", \"cveTags\": [{\"tags\": [\"disputed\"], \"sourceIdentifier\": \"cve@mitre.org\"}], \"metrics\": {\"cvssMetricV31\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"scope\": \"UNCHANGED\", \"version\": \"3.1\", \"baseScore\": 5.3, \"attackVector\": \"NETWORK\", \"baseSeverity\": \"MEDIUM\", \"vectorString\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N\", \"integrityImpact\": \"NONE\", \"userInteraction\": \"NONE\", \"attackComplexity\": \"LOW\", \"availabilityImpact\": \"NONE\", \"privilegesRequired\": \"NONE\", \"confidentialityImpact\": \"LOW\"}, \"impactScore\": 1.4, \"exploitabilityScore\": 3.9}]}, \"published\": \"2023-08-15T17:15:12.187\", \"references\": [{\"url\": \"https://github.com/python/cpython/issues/105987\", \"tags\": [\"Exploit\", \"Issue Tracking\", \"Patch\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://github.com/python/cpython/issues/105987\", \"tags\": [\"Exploit\", \"Issue Tracking\", \"Patch\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}], \"vulnStatus\": \"Modified\", \"weaknesses\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"description\": [{\"lang\": \"en\", \"value\": \"NVD-CWE-Other\"}]}], \"descriptions\": [{\"lang\": \"en\", \"value\": \"An issue in Python cpython v.3.7 allows an attacker to obtain sensitive information via the _asyncio._swap_current_task component. NOTE: this is disputed by the vendor because (1) neither 3.7 nor any other release is affected (it is a bug in some 3.12 pre-releases); (2) there are no common scenarios in which an adversary can call _asyncio._swap_current_task but does not already have the ability to call arbitrary functions; and (3) there are no common scenarios in which sensitive information, which is not already accessible to an adversary, becomes accessible through this bug.\"}, {\"lang\": \"es\", \"value\": \"Un problema en Python cpython v.3.7 permite a un atacante obtener informaci\\u00f3n sensible a trav\\u00e9s del componente _asyncio._swap_current_task. NOTA: esto es discutido por el vendedor porque (1) ni la versi\\u00f3n 3.7 ni ninguna otra est\\u00e1 afectada (es un fallo en algunas versiones previas a la 3.12); (2) no hay escenarios comunes en los que un adversario pueda llamar a _asyncio._swap_current_task pero no tenga ya la capacidad de llamar a funciones arbitrarias; y (3) no hay escenarios comunes en los que informaci\\u00f3n sensible, que no est\\u00e9 ya accesible para un adversario, se vuelva accesible a trav\\u00e9s de este fallo.\"}], \"lastModified\": \"2024-11-21T08:14:24.253\", \"configurations\": [{\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:python:python:3.13.0:alpha0:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"3BA51E41-D221-431F-870F-536AF2867B50\"}], \"operator\": \"OR\"}]}], \"sourceIdentifier\": \"cve@mitre.org\"}}\n",
    "LastUpdate": 0,
    "VendorL": [
      "python"
    ],
    "ProductL": [
      "python"
    ],
    "Software_Repo_Mappings": []
  },
  "Software_Repo_Mapping_Conditions": [
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:3.13.0:alpha0:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    }
  ]
}