{
  "Software_Repo_MappingId": null,
  "Software_RepoId": "f6b863cd-8f1c-4583-8bc5-ee59e86e5cf1",
  "Software_Name": "Python 3.12.5 (64-bit)",
  "CVEID": "CVE-2017-18207",
  "Summary": "The Wave_read._read_fmt_chunk function in Lib/wave.py in Python through 3.6.4 does not ensure a nonzero channel value, which allows attackers to cause a denial of service (divide-by-zero and exception) via a crafted wav format audio file. NOTE: the vendor disputes this issue because Python applications \"need to be prepared to handle a wide variety of exceptions.",
  "LastUpdate": 0,
  "CVEE": {
    "CVEEId": "CVE-2017-18207",
    "CVSS_V2_baseScore": 4.3,
    "CVSS_V2_Data": "{\"version\":\"2.0\",\"baseScore\":4.3,\"accessVector\":\"NETWORK\",\"vectorString\":\"AV:N/AC:M/Au:N/C:N/I:N/A:P\",\"authentication\":\"NONE\",\"integrityImpact\":\"NONE\",\"accessComplexity\":\"MEDIUM\",\"availabilityImpact\":\"PARTIAL\",\"confidentialityImpact\":\"NONE\",\"scope\":null,\"attackVector\":null,\"baseSeverity\":null,\"userInteraction\":null,\"attackComplexity\":null,\"privilegesRequired\":null}",
    "CVSS_V3_baseScore": 6.5,
    "CVSS_V3_Data": "{\"version\":\"3.0\",\"baseScore\":6.5,\"accessVector\":null,\"vectorString\":\"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H\",\"authentication\":null,\"integrityImpact\":\"NONE\",\"accessComplexity\":null,\"availabilityImpact\":\"HIGH\",\"confidentialityImpact\":\"NONE\",\"scope\":\"UNCHANGED\",\"attackVector\":\"NETWORK\",\"baseSeverity\":\"MEDIUM\",\"userInteraction\":\"REQUIRED\",\"attackComplexity\":\"LOW\",\"privilegesRequired\":\"NONE\"}",
    "PublishedDate": "2018-03-01T05:29:00.227",
    "ModifyDate": "2024-11-21T03:19:34.033",
    "VulnStatus": "Modified",
    "JsonData": "{\"id\": \"CVE-2017-18207\", \"summary\": \"The Wave_read._read_fmt_chunk function in Lib/wave.py in Python through 3.6.4 does not ensure a nonzero channel value, which allows attackers to cause a denial of service (divide-by-zero and exception) via a crafted wav format audio file. NOTE: the vendor disputes this issue because Python applications \\\"need to be prepared to handle a wide variety of exceptions.\", \"created_at\": \"2018-03-01T05:29:00Z\", \"updated_at\": \"2024-11-21T03:19:34Z\", \"cvss\": {\"v2\": 4.3, \"v3\": 6.5}, \"vendors\": {\"python\": [\"python\"]}, \"cwes\": [\"CWE-369\"], \"raw_nvd_data\": {\"id\": \"CVE-2017-18207\", \"cveTags\": [{\"tags\": [\"disputed\"], \"sourceIdentifier\": \"cve@mitre.org\"}], \"metrics\": {\"cvssMetricV2\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"version\": \"2.0\", \"baseScore\": 4.3, \"accessVector\": \"NETWORK\", \"vectorString\": \"AV:N/AC:M/Au:N/C:N/I:N/A:P\", \"authentication\": \"NONE\", \"integrityImpact\": \"NONE\", \"accessComplexity\": \"MEDIUM\", \"availabilityImpact\": \"PARTIAL\", \"confidentialityImpact\": \"NONE\"}, \"acInsufInfo\": false, \"impactScore\": 2.9, \"baseSeverity\": \"MEDIUM\", \"obtainAllPrivilege\": false, \"exploitabilityScore\": 8.6, \"obtainUserPrivilege\": false, \"obtainOtherPrivilege\": false, \"userInteractionRequired\": true}], \"cvssMetricV30\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"scope\": \"UNCHANGED\", \"version\": \"3.0\", \"baseScore\": 6.5, \"attackVector\": \"NETWORK\", \"baseSeverity\": \"MEDIUM\", \"vectorString\": \"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H\", \"integrityImpact\": \"NONE\", \"userInteraction\": \"REQUIRED\", \"attackComplexity\": \"LOW\", \"availabilityImpact\": \"HIGH\", \"privilegesRequired\": \"NONE\", \"confidentialityImpact\": \"NONE\"}, \"impactScore\": 3.6, \"exploitabilityScore\": 2.8}]}, \"published\": \"2018-03-01T05:29:00.227\", \"references\": [{\"url\": \"http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html\", \"source\": \"cve@mitre.org\"}, {\"url\": \"https://bugs.python.org/issue32056\", \"tags\": [\"Issue Tracking\", \"Vendor Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://bugs.python.org/issue32056\", \"tags\": [\"Issue Tracking\", \"Vendor Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}], \"vulnStatus\": \"Modified\", \"weaknesses\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"description\": [{\"lang\": \"en\", \"value\": \"CWE-369\"}]}], \"descriptions\": [{\"lang\": \"en\", \"value\": \"The Wave_read._read_fmt_chunk function in Lib/wave.py in Python through 3.6.4 does not ensure a nonzero channel value, which allows attackers to cause a denial of service (divide-by-zero and exception) via a crafted wav format audio file. NOTE: the vendor disputes this issue because Python applications \\\"need to be prepared to handle a wide variety of exceptions.\"}, {\"lang\": \"es\", \"value\": \"** EN DISPUTA ** La funci\\u00f3n Wave_read._read_fmt_chunk en Lib/wave.py en Python, hasta la versi\\u00f3n 3.6.4, no garantiza un valor de canal nonzero, lo que permite que atacantes remotos provoquen una denegaci\\u00f3n de servicio (error de divisi\\u00f3n entre cero y cierre inesperado de la aplicaci\\u00f3n) mediante un archivo de audio wav manipulado. NOTA: el vendedor informa que las aplicaciones de Python \\\"necesitan estar preparadas para manejar una amplia variedad de excepciones\\\".\"}], \"lastModified\": \"2024-11-21T03:19:34.033\", \"configurations\": [{\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"3CCA920B-9E95-4960-B3B7-40A704F2973D\", \"versionEndIncluding\": \"3.6.4\"}], \"operator\": \"OR\"}]}], \"sourceIdentifier\": \"cve@mitre.org\"}}\n",
    "LastUpdate": 0,
    "VendorL": [
      "python"
    ],
    "ProductL": [
      "python"
    ],
    "Software_Repo_Mappings": []
  },
  "Software_Repo_Mapping_Conditions": [
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": "3.6.4",
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    }
  ]
}